Cruzeirao/src/main/java/sistema/mb/CampeonatoMB.java
package sistema.mb;



import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import sistema.entidades.Campeonato;
import sistema.entidades.Categoria;
import sistema.entidades.Fase;
import sistema.service.CampeonatoService;


@ManagedBean
@SessionScoped
public class CampeonatoMB {

	private CampeonatoService campeonatoService = new CampeonatoService();
	private Campeonato novoCampeonato = new Campeonato();
	private Campeonato campeonatoAtual;
	private Categoria novaCategoria;
	
	public String salvar() {
		campeonatoService.salvar(novoCampeonato);
		novoCampeonato = new Campeonato();
		return "menu";
	}
	
	public List <Campeonato> getCampeonatos()
	{
		return campeonatoService.getCampeonatos();
	}

	public Campeonato getNovoCampeonato() {
		return novoCampeonato;
	}

	public void setNovoCampeonato(Campeonato novoCampeonato) {
		this.novoCampeonato = novoCampeonato;
	}

	public Campeonato getCampeonatoAtual() {
		return campeonatoAtual;
	}

	public void setCampeonatoAtual(Campeonato campeonatoAtual) {
		this.campeonatoAtual = campeonatoAtual;
	}
	
	/*
	public String verCategoriasNome(String idNome) {
		campeonatoAtual = campeonatoService.getCampeonatoByNome(idNome);
		return "listarCategoriaCampeonato";
	}
	
	public String verCategorias(Campeonato campeonato) {
		campeonatoAtual = campeonatoService.getCampeonatoByNome(campeonato.getNome());
		return "listarCategoriaCampeonato";
	}
	*/
	public String criarCategorias() {
		novaCategoria = new Categoria();
		return "cadastroCategoria";
	}
	
	public String salvarCategoria()
	{
		novoCampeonato.addCategorias(novaCategoria);
		novaCategoria.setCampeonato(novoCampeonato);
		return "listarCategoriaCampeonato";
	}

	public Categoria getNovaCategoria() {
		return novaCategoria;
	}

	public void setNovaCategoria(Categoria novacategoria) {
		this.novaCategoria = novacategoria;
	}	
}

Cruzeirao/src/main/java/sistema/mb/CategoriaMB.java
package sistema.mb;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import sistema.entidades.Categoria;
import sistema.entidades.Fase;
import sistema.service.CategoriaService;

@ManagedBean
@SessionScoped

public class CategoriaMB {

	private CategoriaService categoriaService = new CategoriaService();
	private Categoria novaCategoria = new Categoria();
	private Categoria categoriaAtual;
	private Fase novaFase;
	
	public String salvar() {
		categoriaService.salvar(novaCategoria);
		novaCategoria = new Categoria();
		return "menu";
	}
	
	/*
	public String verFasesNome(String idNome)
	{
		categoriaAtual = categoriaService.getCategoriaByNome(idNome);
		return "listarFaseCategoria";
	}
	
	public String verFases(Categoria categoria)
	{
		categoriaAtual = categoriaService.getCategoriaByNome(categoria.getNome());
		return "listarFaseCategoria";
	}
	*/
	public List<Categoria> getCategorias(){
		return categoriaService.getCategorias();
	}

	public Categoria getNovaCategoria() {
		return novaCategoria;
	}

	public void setNovaCategoria(Categoria novaCategoria) {
		this.novaCategoria = novaCategoria;
	}

	public Categoria getCategoriaAtual() {
		return categoriaAtual;
	}

	public void setCategoriaAtual(Categoria categoriaAtual) {
		this.categoriaAtual = categoriaAtual;
	}
	
	public String criarFases() {
		novaFase = new Fase();
		return "cadastroFase";
	}
	
	public String salvarFase()
	{
		novaCategoria.addFases(novaFase);
		novaFase.setCategoria(novaCategoria);
		return "listarFaseCategoria";
	}

	public Fase getNovaFase() {
		return novaFase;
	}

	public void setNovaFase(Fase novaFase) {
		this.novaFase = novaFase;
	}
	
	
	

}

Cruzeirao/src/main/java/sistema/mb/EquipeMB.java
package sistema.mb;


import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import sistema.entidades.Equipe;

import sistema.service.EquipeService;

@ManagedBean
@SessionScoped
public class EquipeMB {

	private EquipeService equipeService = new EquipeService();
	private Equipe equipe = new Equipe();
	private Equipe novaEquipe;
	
	public String salvar() {
		equipeService.salvar(novaEquipe);
		novaEquipe = new Equipe();
		return "menu";
	}
	
	public List <Equipe> getEquipes()
	{
		return equipeService.getEquipes();
	}
	
	public Equipe getEquipe() {
		return equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}
}

Cruzeirao/src/main/java/sistema/mb/UsuarioMB.java
package sistema.mb;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import sistema.entidades.Campeonato;
import sistema.entidades.Equipe;
import sistema.entidades.Usuario;
import sistema.service.UsuarioService;


@ManagedBean
@SessionScoped
public class UsuarioMB {
	
	private UsuarioService usuarioService = new UsuarioService();
	private Usuario novoUsuario = new Usuario();
	private Equipe novaEquipe;
	private Campeonato novoCampeonato;
	private Usuario usuarioAtual;
	
	
	public String salvar() {
		usuarioService.salvar(novoUsuario);
		novoUsuario = new Usuario();
		return "menu";
		
	}
	
	public List <Usuario> getUsuarios()
	{
		return usuarioService.getUsuarios();
	}
	
	/*
	public String verEquipesCPF(String cpf)
	{
		usuarioAtual = usuarioService.getUsuarios();
		return "listarEquipeUsuario";
	}
	
	
	public String verEquipes(Usuario usuario)
	{
		usuarioAtual = usuarioService.getUsuarioId(usuario.getCpf());
		return "listarEquipeUsuario";
	}
	
	
	public String verCampeonatosCPF(String cpf)
	{
		usuarioAtual = usuarioService.getUsuarioId(cpf);
		return "listarCampeonatoUsuario";
	}
	
	
	public String verCampeonatos(Usuario usuario)
	{
		usuarioAtual = usuarioService.getUsuarioId(usuario.getCpf());
		return "listarCampeonatoUsuario";
	}
	*/
	
	public String criarEquipes()
	{
		novaEquipe = new Equipe();
		return "cadastroEquipe";
	}
	
	public String criarCampeonatos()
	{
		novoCampeonato = new Campeonato();
		return "cadastroCampeonato";
	}
	

	public String salvarEquipe()
	{
		usuarioAtual.addEquipes(novaEquipe);
		novaEquipe.setUsuario(usuarioAtual);
		return "listarEquipeUsuario";
	}
	
	
	public String salvarCampeonato()
	{
		usuarioAtual.addCampeonatos(novoCampeonato);
		novoCampeonato.setUsuario(usuarioAtual);
		return "listarCampeonatoUsuario";
	}
	
	public Usuario getNovoUsuario() {
		return novoUsuario;
	}


	public void setNovoUsuario(Usuario novoUsuario) {
		this.novoUsuario = novoUsuario;
	}


	public Equipe getNovaEquipe() {
		return novaEquipe;
	}

	public void setNovaEquipe(Equipe novaEquipe) {
		this.novaEquipe = novaEquipe;
	}
	
	public Campeonato getNovoCampeonato() {
		return novoCampeonato;
	}
	
	public void setNovoCampeonato(Campeonato novocampeonato) {
		this.novoCampeonato = novocampeonato;
	}


	public Usuario getUsuarioAtual() {
		return usuarioAtual;
	}


	public void setUsuarioAtual(Usuario usuarioAtual) {
		this.usuarioAtual = usuarioAtual;
	}
	
	
	
}

Cruzeirao/src/main/webapp/pages/cadastroCampeonato.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
			
	<ui:define name="principal">
		<div class="principal" align="center">
			<h1>Cadastro de Campeonato</h1>
			<h:form id="formCampeonato">
			     
			      <h:panelGrid columns="2">
			           <p:outputLabel value="Nome: "/>
			           <p:inputText value="#{usuarioMB.novoCampeonato.nome}"/> 
			          
			           <p:outputLabel value="Data de Inscricao: "/>
			           <p:calendar value="#{usuarioMB.novoCampeonato.dataInicioCampeonato}"/>   
			           
			           <p:outputLabel value="Data Final de Inscricao: "/>
			           <p:calendar value="#{usuarioMB.novoCampeonato.dataFimInscricao}"/>
			          
			           <p:outputLabel value="Data Inicio do Campeonato: "/>
			           <p:calendar value="#{usuarioMB.novoCampeonato.dataInicioCampeonato}"/>
			           
			           <p:outputLabel value="Data Final do Campeonato:"/>
			           <p:calendar value="#{usuarioMB.novoCampeonato.dataFimCampeonato}"/>
			           
			           <p:outputLabel value="Valor da Taxa: "/>
			           <p:inputText value="#{usuarioMB.novoCampeonato.valorTaxa}"/>
			        
			     </h:panelGrid>  
			     <p:commandButton action="#{usuarioMB.salvarCampeonato}"  value="Salvar" update=":formCampeonato" />
		     </h:form>
		</div>
	</ui:define>			
</ui:composition>

Cruzeirao/src/main/webapp/pages/cadastroGrupo.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="principal">
		<div class="principal" align="center">
 			<h:form id="formGrupo">
     			<h:panelGrid columns="2">
			           <p:outputLabel value="Nome: "/>
			           <p:inputText value="#{grupoMB.novoGrupo.nome}"/> 
			           
			           <p:outputLabel value="Fase: "/>
			           <p:inputText value="#{grupoMB.novoGrupo.fase}"/>  
			            
			           <p:outputLabel value="Numero: "/>
			           <p:inputText value="#{grupoMB.novoGrupo.numero}"/>
			                   
			     </h:panelGrid>     
			     <p:commandButton value="Salvar" action="#{grupoMB.salvar}" update=":formGrupo"	/>
			 </h:form>
		</div>
	</ui:define>			
</ui:composition>

Cruzeirao/src/main/webapp/pages/cadastroInscricao.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="principal">
		<div class="principal" align="center">
			<h1>Cadastro de Inscricao</h1>
			<h:form id="formInscricao">
			     <h:panelGrid columns="2">
			           <p:outputLabel value="Numero: "/>
			           <p:inputText value="#{inscricaoMB.inscricao.numero}"/> 
			           
			           <p:outputLabel value="Pagamento: "/>
			           <p:inputText value="#{inscricaoMB.inscricao.pagamento}"/> 
			             
			           <p:outputLabel value="Validada: "/>
			           <p:inputText value="#{inscricaoMB.inscricao.validada}"/>
			           
			     </h:panelGrid>     
			     <p:commandButton value="Salvar"
			     				  action="#{inscricaoMB.salvar}"
			     				  update=":formInscricao"	
			     />
			
			</h:form>
		</div>
	</ui:define>
</ui:composition>

Cruzeirao/src/main/webapp/pages/cadastroUsuario.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="principal">
		<div class="principal" align="center">
			<h1>Cadastro de Usuario</h1>
			<h:form id="formUsuario">
			<h:panelGrid columns="2">
			     		<p:outputLabel value="Email: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.email}"/>
			     
			           <p:outputLabel value="Nome: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.nome}"/> 
			          
			           <p:outputLabel value="Data de Nascimento: "/>
			           <p:calendar value="#{usuarioMB.novoUsuario.dataNascimento}"/> 
			           
			           <p:outputLabel value="Telefone Fixo: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.telefoneFixo}"/>
			           
			           <p:outputLabel value="Telefone Movel: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.telefoneMovel}"/>
			           
			           <p:outputLabel value="Endereco: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.endereco}"/>  
			           
			           <p:outputLabel value="RG: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.rg}"/>
			           
			           <p:outputLabel value="CPF: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.cpf}"/>
			           
			           <p:outputLabel value="Sexo: "/>
			           <p:inputText value="#{usuarioMB.novoUsuario.sexo}"/>
			             </h:panelGrid>    
			     
			     <p:commandButton   action="#{usuarioMB.salvar}"  value="Salvar" update=":formUsuario" />
			
			</h:form>
		</div>
	</ui:define>
</ui:composition>

Cruzeirao/src/main/webapp/pages/cartao.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="principal">
		<div class="principal" align="center">
			 <h:form id="formCartao">
			     <h:panelGrid columns="2">
			           <p:outputLabel value="Cartao Vermelho: "/>
			           <p:inputText value="#{cartaoMB.cartao.vermelho}"/> 
			           
			           <p:outputLabel value="Cartao Amarelo: "/>
			           <p:inputText value="#{cartaoMB.cartao.amarelo}"/>
			                
			     </h:panelGrid>     
			     <p:commandButton value="Salvar" action="#{cartaoMB.salvar}" update=":formCartao" />
				<br>
				</br>
			     <p:dataTable var="cartao" value="#{cartaoMB.lista}">
			       <p:column headerText="Cartao Vermelho">
			          <p:outputLabel value="#{cartao.vermelho}"/>
			       </p:column>
			       <p:column headerText="Cartao Amarelo">
			          <p:outputLabel value="#{cartao.amarelo}"/>
			       </p:column>
			     </p:dataTable>
			 </h:form>
		</div>
	</ui:define>
</ui:composition>

Cruzeirao/src/main/webapp/pages/fase.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="principal">
		<div class="principal" align="center">
			 <h:form id="formFase">
			     <h:panelGrid columns="2">
			           <p:outputLabel value="Data de Inicio: "></p:outputLabel>
			           <p:calendar value="#{faseMB.fase.dataInicio}"/>
			           
			           <p:outputLabel value="Data Final: "></p:outputLabel>
			           <p:calendar value="#{faseMB.fase.dataFim}"/>
			             
			           <p:outputLabel value="Validata: "/>
			           <p:inputText value="#{faseMB.fase.numero}"/>
			           
			     </h:panelGrid>     
			     <p:commandButton value="Salvar" action="#{faseMB.salvar}" update=":formFase" />
				 <br>
				 </br>
			     <p:dataTable var="fase" value="#{faseMB.lista}">
						<p:column headerText="Data Inicial">
			          		<h:outputText/>
			           		<h:outputText value="#{campeonato.dataInicio}">
			                <f:convertDateTime pattern="dd/MM/yyyy" />
			            </h:outputText>
			       </p:column>
			       
			     	 <p:column headerText="Data Final">
			          <h:outputText/>
			            <h:outputText value="#{fase.dataFim}">
			                <f:convertDateTime pattern="dd/MM/yyyy" />
			            </h:outputText>
			       </p:column>
			       
			       <p:column headerText="Numero">
			          <p:outputLabel value="#{fase.numero}"/>
			       </p:column>
			    
			     </p:dataTable>
			     
			 </h:form>
		</div>
	</ui:define>
</ui:composition>

Cruzeirao/src/main/webapp/pages/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<style>
	.topnav {
    	background-color: #333;
    	overflow: hidden;
	}

	.topnav a {
	    float: left;
	    color: #f2f2f2;
	    text-align: center;
	    padding: 14px 16px;
	    text-decoration: none;
	    font-size: 17px;
	}
	
	.topnav a:hover {
	    background-color: #ddd;
	    color: black;
	}
	
	.topnav a.active {
	    background-color: #4CAF50;
	    color: white;
	}
	
	#content img {
	    top: 0px;
	    right: 0px;
	    height: 150px;
	}

	</style>
	<body bgcolor = "#809C48"> 
	 <div class="topnav">
		  <a href="menu.xhtml">Menu</a>
		  <a href="listarCampeonatos.xhtml">Campeonatos</a>
		  <a href="listarEquipes.xhtml">Equipes</a>
		  <a href="listarCategorias.xhtml">Categorias</a>
		  <a href="listarFases.xhtml">Fases</a>
		  <a href="listarGrupo.xhtml">Grupos</a>
		  <a href="listarInscricoes.xhtml">Inscrições</a>
		  <a href="listarPartidas.xhtml">Partidas</a>
		  <a href="listarUsuario.xhtml">Usuarios</a>
	</div> 
	<br>
	</br>	
	<div id="content">
		<a href="../pages/menu.xhtml"> <img
			src="../Images/Logo.png" alt="Campeonato 2018"/>
		</a>
	</div>
	</body>
</ui:composition>

Cruzeirao/src/main/webapp/pages/listarCampeonatos.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	
	<ui:define name="principal">
		<div class="principal" align="center">
			<h1>Campeonatos Cadastradas</h1>
			<h:form>
			
				<p:dataTable var="campeonato" value="#{usuarioMB.usuarioAtual.campeonatos}">
		       <p:column headerText="Nome">
		          <p:outputLabel value="#{campeonato.nome}"/>
		       </p:column>
		       
		     	<p:column headerText="Data de Inscricao">
		     	<h:outputText/>
		            <h:outputText value="#{campeonato.dataInicioInscricao}">
		                <f:convertDateTime pattern="dd/MM/yyyy" />
		            </h:outputText>
		       </p:column>
		       
		       <p:column headerText="Data Final de Inscricao">
		          <h:outputText/>
		            <h:outputText value="#{campeonato.dataFimInscricao}">
		                <f:convertDateTime pattern="dd/MM/yyyy" />
		            </h:outputText>
		       </p:column>
		       
		     <p:column headerText="Data Inicio do Campeonato">
		          <h:outputText/>
		            <h:outputText value="#{campeonato.dataInicioCampeonato}">
		                <f:convertDateTime pattern="dd/MM/yyyy" />
		            </h:outputText>
		       </p:column>
		       
		       <p:column headerText="Data Final do Campeonato">
		          <h:outputText/>
		            <h:outputText value="#{campeonato.dataFimCampeonato}">
		                <f:convertDateTime pattern="dd/MM/yyyy" />
		            </h:outputText>
		       </p:column>
		       
		       <p:column headerText="Valor da Taxa">
		          <p:outputLabel value="#{campeonato.valorTaxa}"/>
		       </p:column>
	    
		     </p:dataTable>
			</h:form>
		</div>
	</ui:define>
</ui:composition>

Cruzeirao/src/main/webapp/pages/listarCategoriaCampeonato.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="principal">
		<div class="principal" align="center">
			<h1>Dados do usuario:</h1>
			<p:outputLabel value="CPF: #{usuarioMB.usuarioAtual.cpf}"  />
			<br/>
			<p:outputLabel value="Nome: #{usuarioMB.usuarioAtual.nome}"  />
			
			<h1>Categorias cadastrados:</h1>
			<h:form>				
				<h:commandLink value="Nova Categoria" action="#{campeonatoMB.criarCategorias()}" />
				<h3>Categorias Cadastradas</h3>
				<p:dataTable  value="#{campeonatoMB.novoCampeonato.categorias}" var="cat" border="1" >					
					<p:column headerText="Nome">
						<p:outputLabel value="#{cat.nome}"/>
					</p:column>
						       
					<p:column headerText="Nascidos a partir de:">
						<h:outputText/>
						<h:outputText value="#{cat.nascidosApartirDe}">
						</h:outputText>
					</p:column>	\
								       
					<p:column headerText="Numero Minimo de Jogadores">
						<p:outputLabel value="#{cat.minJogadores}"/>
					</p:column>	
								       
					<p:column headerText="Numero Maximo de Jogadores">
						<p:outputLabel value="#{cat.maxJogadores}"/>
					</p:column>	
								       
					<p:column headerText="Sexo">
						<p:outputLabel value="#{cat.sexo}"/>
					</p:column>	
								    
					<p:column headerText="Opções" >
						<p:commandLink action="#{categoriaMB.verFases(cat)}" value="Ver Fases" />
					</p:column>	    
				</p:dataTable>
			  </h:form>
		</div>
	</ui:define>
</ui:composition>

Cruzeirao/src/main/webapp/pages/listarEquipeUsuario.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="principal">
		<div class="principal" align="center">
		<h1>Dados do usuario:</h1>
		<p:outputLabel value="CPF: #{usuarioMB.usuarioAtual.cpf}"  />
		<br/>
		<p:outputLabel value="Nome: #{usuarioMB.usuarioAtual.nome}"  />
		
		    <h1>Equipes cadastrados:</h1>
			<h:form>
				
			    
			    <h:commandLink value="Nova Equipe" action="#{usuarioMB.criarEquipes()}" />
			    <h3>Equipes Cadastradas</h3>
				<p:dataTable  value="#{usuarioMB.usuarioAtual.equipes}" var="equipe" border="1" >
			    
			    <p:column headerText="Nome">
				     <p:outputLabel  value="#{equipe.nome}"/>
				</p:column>
				
				<p:column headerText="Data Fundacao">
				     <p:calendar value="#{equipe.dataFundacao}"/>
				</p:column>
				
				<p:column headerText="Cidade">
				     <p:outputLabel  value="#{equipe.cidade}"/>
				</p:column>
				</p:dataTable>		
			</h:form>
		</div>
	</ui:define>
</ui:composition>

Cruzeirao/src/main/webapp/pages/menu.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	
	<ui:define name="principal">
		<div class="principal" align="center">
			<h1>Menu Principal</h1>
				<form method="get" action="cadastroUsuario.xhtml">
				    <button type="submit">Registrar Usuario</button>
				</form>
		</div>
	</ui:define>
	
</ui:composition>

Cruzeirao/src/main/webapp/pages/usuario.xhtml
<ui:composition template="default.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	
	<div class="principal" align="center">
			<h1>Usuario</h1>
				<h:form>
					<p:dataTable value="#{usuarioMB.usuarios}" var="usuario">
			     
			       <p:column headerText="Email">
			          <p:outputLabel value="#{usuario.email}"/>
			       </p:column>
			       
			       <p:column headerText="Nome">
			          <p:outputLabel value="#{usuario.nome}"/>
			       </p:column>
			       
			   	<p:column headerText="Data de Nascimento">
		    	<h:outputText/>
				<h:outputText value="#{usuario.dataNascimento}">
		       	<f:convertDateTime pattern="dd/MM/yyyy" />
			       </h:outputText>
			       </p:column>
			       			       <p:column headerText="Telefone Fixo">
		          <p:outputLabel value="#{usuario.telefoneFixo}"/>
		       </p:column>
		       
			      <p:column headerText="Telefone Movel">
			         <p:outputLabel value="#{usuario.telefoneMovel}"/>
			      </p:column>
			      
			      <p:column headerText="Endereco">
			         <p:outputLabel value="#{usuario.endereco}"/>
			      </p:column>
			       			       <p:column headerText="RG">
		          <p:outputLabel value="#{usuario.rg}"/>
		       </p:column>
		       
			      <p:column headerText="CPF">
			         <p:outputLabel value="#{usuario.cpf}"/>
			      </p:column>
			      
			      <p:column headerText="Sexo">
			         <p:outputLabel value="#{usuario.sexo}"/>
			    </p:column>
			       			       <p:column headerText="Opções" >
				<p:commandLink action="#{usuarioMB.verEquipes(usuario)}" value="Ver Equipes" />
				</p:column>
					<p:column headerText="Opções" >					
					<p:commandLink action="#{usuarioMB.verCampeonatos(usuario)}" value="Ver Campeonatos" />
				</p:column>
				</p:dataTable>
			</h:form>
		</div>
	
</ui:composition>